services:
  backend: &backend
    build:
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0
    env_file:
      - .env.local
      - .env.local.secret
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - minio
    tty: true
    stdin_open: true

  db:
    platform: linux/x86_64
    image: mysql:8.0.23 # https://docs.amazonaws.cn/en_us/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.3020.html
    command: mysqld --default_authentication_plugin=mysql_native_password 
    env_file: .env.local
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2022-04-26T01-20-24Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local
