name: backend-deploy-to-sky1
on:
  push:
    branches:
      - 'main'

jobs:
  push-to-bucket:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::171178482625:role/cas-github-actions
          role-session-name: MySessionName
      - run: aws sts get-caller-identity
      - uses: actions/checkout@v3
      - run: |
          echo "MYSQL_DATABASE_NAME=cas_dev_sky1" >> backend/.codebuild/dev/web_api.env
          echo "AWS_SQS_HOST=https://sqs.ap-northeast-1.amazonaws.com/171178482625/cas-web-api-sqs-sky1" >> backend/.codebuild/dev/web_api.env
      - run: |
          cd backend/
          echo $GITHUB_SHA > github_sha
          zip -r source.zip . -x *.git/*
        env:
          GITHUB_SHA: ${{ github.sha }}
      - run: aws s3api put-object --bucket cas-codebuild-source-dev --key backend-sky1.zip --body backend/source.zip
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
